version: '3'
services:
  audionook_dev:
    image: <your>/<image_name>:latest
    container_name: audionook_dev
    environment:
      WATCHFILES_FORCE_POLLING: true
      SECRET_KEY: ${SECRET_KEY}
      WIKI_USER_AGENT: ${WIKI_USER_AGENT}
      ENVIRON_LOGLEVEL: ${ENVIRON_LOGLEVEL}
      ENVIRON: ${ENVIRON}
    volumes:
      - /path/to/audiobooks:/app/stacks
      # Optional Mounts for data persitence
      - /path/to/db/dev:/app/db
      - /path/to/logs/dev:/app/logs
      # Optional txt file with preselected ISBNs to help gather metadata
      - /path/to/ISBNoverrides.txt:/app/stacks/ISBNoverrides.txt
      # Required extra mounts for dev container
      # scrivapi
      - /path/to/repo/src:/app/src
      - /path/to/repo/bin/run_dev.sh:/app/bin/run_dev.sh
      - /path/to/repo/bin/dev-supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - /path/to/repo/docker/.env:/app/bin/.env
      # nginx
      - /path/to/repo/web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /path/to/repo/web/nginx/error-modules:/etc/nginx/error-modules
      - /path/to/repo/web/nginx/sites-available/dev-audionook.conf:/etc/nginx/sites-available/default
      - /path/to/repo/web/nginx/sites-enabled:/etc/nginx/sites-enabled
      # web
      - /path/to/repo/web/flutter/build/web:/var/www/audionook
      - /path/to/repo/web/html:/var/www/default
    ports:
      - public-port:80
